version: '2'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      target: runner
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
